### ISSUE TITLE
Inventaire Ansible

### ISSUE THREAD

**Issue by spr-github** [dunod-docker/docker-exemples-edition3#1]
Bonjour,

Dans le chapitre 2.3.2 p45 de l'ouvrage, il est mentionné que "toutes les machines de l'inventaire" ne représente dans ce cas qu'un seul hôte au regard de l'exemple précédent. Or l'exemple en question qui se trouve à la page précédente fait état du fichier **/etc/ansible/hosts** qui contient 5 hosts (2 frontend et 3 backend). Dans ce cas, le "toutes les machines de l'inventaire" ne devrait-il pas réprésenter les 5 hôtes ?

Merci pour votre retour

**Comment by pycloux** [comment]
Bonjour @spr-github ,

Votre remarque est tout a fait pertinente.
Il s'agit clairement d'une typo.
"all" dans le cas d'un inventaire de plusieurs machines signifie bien toutes les machines.

Merci beaucoup, j'ajoute ce point dans la documentation en ligne.

**Comment by pycloux** [comment]
La page ERRATA est mise à jour : https://github.com/dunod-docker/docker-exemples-edition3/blob/master/content/ERRATA.md
